server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-url:
        defaultZone: http://localhist:8761/eureka
      instance:
        hostname: localhost

management:
  server:
    port: 9012
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,env,beans,loggers,metrics
    jmx:
      exposure:
        include: health,info,env,beans,loggers,metrics
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
